### PR TITLE
Improve SQL statements containing 'and'

### PR DESCRIPTION
**Pull request by nonchris**
As discussed in #3

### CODE REVIEW

**Comment by nonchris** [comment]
I did it :raised_hands:

**Comment by MayNiklas** [comment]
I'm looking forward to this feature!!

**Comment by nonchris** [comment]
It will change the bot 4 ever

**Review by MayNiklas — APPROVED** [review]
Looks great to me!
Very nice improvement to the project 👍

Thanks for collaborating! 🚀

**Pull request merged**
